server:
  port: 8765
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book1
          uri: lb://book-service
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/